### ISSUE TITLE
M3 preset causes mosaics

### ISSUE THREAD

**Issue by jetta** [OpenVisualCloud/SVT-HEVC#156]
Hi, I tested the encoder using the following ffmpeg command:

`ffmpeg -y -i xcp_1080p.mp4 -c:v libsvt_hevc -rc 1 -b:v 5M -tune 0 -preset 3 -c:a aac -f mpegts xcp_1080p_svt_m3.ts`

The output file is OK when using M6, M9 preset, but it has mosaics at 36s under M3 preset.:

![image](https://user-images.githubusercontent.com/39965/54743608-8fa1cc80-4bff-11e9-91b8-512789e25f55.png)

**ffmpeg log:**
[log.txt](https://github.com/OpenVisualCloud/SVT-HEVC/files/2991499/log.txt)

**source video file:**
[https://pan.baidu.com/s/1IGH7PdqtbNriaUD9iXKnxg](https://pan.baidu.com/s/1IGH7PdqtbNriaUD9iXKnxg)

**output video file:**
[https://pan.baidu.com/s/13pP-PbhUj9cDTRBdx_hmCQ](https://pan.baidu.com/s/13pP-PbhUj9cDTRBdx_hmCQ)

**Comment by tianjunwork** [comment]
@jetta Thanks for your feedback and detailed report.
@jsunintel Could you help to verify the issue here? We don't have Baidu account and can't register without China phone number. Thank you:)

**Comment by jsunintel** [comment]
> 
> 
> @jetta Thanks for your feedback and detailed report.
> @jsunintel Could you help to verify the issue here? We don't have Baidu account and can't register without China phone number. Thank you:)

I am sorry that I can't do it. Baidu Pan is prohibited by the company firewall.

**Comment by tianjunwork** [comment]
Hi @jetta, I can't access Baidu from US. But I can reproduce with the 1080p big bunny video also. 

With -tune 0, -preset 1-4, encoded video show mosaics. -preset 5 and above is fine.
With -tune 1, -preset any,  encoded videos are all fine.
We will work on the fix. Could you use tune 1 if this issue blocks you?

**Comment by tianjunwork** [comment]
@lijing0010 could you also check if your patch fix this issue?

**Comment by intelmark** [comment]
Confirmed this issue still exists with BigBuckBunny_4000f_1920x1080.yuv using HEVC built on 6/12

SvtHevcEncApp.exe -i Z:\SVT\SVT_Testing\yuvs\BigBuckBunny_4000f_1920x1080.yuv -w 1920 -h 1080 -tune 0 -encMode 4 -b C:/testfiles/bbb1080_e4_tune0.hevc
playback shows substantial mosaic/block issues throughout

SvtHevcEncApp.exe -i Z:\SVT\SVT_Testing\yuvs\BigBuckBunny_4000f_1920x1080.yuv -w 1920 -h 1080 -tune 1 -encMode 4 -b C:/testfiles/bbb1080_e4_tune1.hevc
playback looks fine

**Comment by Austin-Hu** [comment]
At first, this was a random issue which could be reproduced with either the xcp_1080p.mp4 clip from @jetta  or the BigBuckBunny bbb_1080p_30fps_10s.mp4 clip from @tianjunwork and @intelmark . It could be reproduced by encoding them with SVT-HEVC, within less than 5 times. And as the latter clip is much shorter, so that one was "easier" to be reproduced.

And I confirmed that with @lijing0010 's [patch](https://github.com/OpenVisualCloud/SVT-HEVC/commit/0a9c8d15cc404fb60ce878214fe5c020d2109ed4) which has been merged, the random issue can not be reproduced any more, after verifying by encoding the 2 clips and playing them separately with 10 times.

So @jetta , please verify your clip with the latest commit of SVT-HEVC master branch. And @tianjunwork  & @intelmark , please also confirm this in your side. Thanks!

**Comment by tianjunwork** [comment]
Confirmed, fixed by #189.
