### ISSUE TITLE
Segmentation fault on AMD CPU using more than 12 cores

### ISSUE THREAD

**Issue by mbake5** [OpenVisualCloud/SVT-HEVC#181]
I am using VMware and if I configure the VM with 12 cores or less then the encode completes without errors.  If I configure 14 or 16 cores then I get a segmentation fault.

mbaker@ubuntu:~/SVT-HEVC/Bin/Release$ ./SvtHevcEncApp -i /mnt/hgfs/C/multimedia/av1/reference_station.yuv -w 1920 -h 1080 -b out.265
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:	SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :	GCC 7.3.0	 64 bit
LIB Build date: Apr 18 2019 16:39:14
-------------------------------------------
Segmentation fault (core dumped)

mbaker@ubuntu:~/SVT-HEVC/Bin/Release$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           16
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD Ryzen 7 1700 Eight-Core Processor
Stepping:            1
CPU MHz:             3800.364
BogoMIPS:            7600.72
Virtualization:      AMD-V
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core cpb ssbd vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xsaves clzero arat npt svm_lock nrip_save vmcb_clean flushbyasid decodeassists overflow_recov succor

**Comment by 1480c1** [comment]
Can you build in debug mode and prepend `gdb --args` to SvtAv1EncApp when running it?

**Comment by mbake5** [comment]
I am not a programmer so I am not sure if I did this correctly.

mbaker@ubuntu:~/SVT-HEVC/Bin/Debug$ sudo gdb --args ./SvtHevcEncApp -i /mnt/hgfs/C/multimedia/av1/reference_station.yuv -w 1920 -h 1080 -b out.265
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git

Reading symbols from ./SvtHevcEncApp...done.

(gdb) run
Starting program: /home/mbaker/SVT-HEVC/Bin/Debug/SvtHevcEncApp -i /mnt/hgfs/C/multimedia/av1/reference_station.yuv -w 1920 -h 1080 -b out.265
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:	SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :	GCC 7.3.0	 64 bit
LIB Build date: Apr 18 2019 16:41:33
-------------------------------------------

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7158cde in EbDeinitEncoder (h265EncComponent=0x0) at /home/mbaker/SVT-HEVC/Source/Lib/Codec/EbEncHandle.c:1528
1528	    EbEncHandle_t *encHandlePtr = (EbEncHandle_t*)h265EncComponent->pComponentPrivate;

**Comment by tianjunwork** [comment]
Could you change the cmake flag “-march=native” to "–mavx" in CMakeLists.txt under root and build it again? Please pull the latest code.

**Comment by tianjunwork** [comment]
Hi @mbake5, any update? With "-mavx", it should run on your AMD CPU.

**Comment by mbake5** [comment]
It didn't compile correctly so I am not sure.

**Comment by tianjunwork** [comment]
Oh, what is the compile error?

**Comment by luigi311** [comment]
Something is wrong in your configuration. Looking at your lscpu it is showing 16 sockets with 1 core each. I am not sure if that will affect it but here is what mine looks like via KVM instead of vmware. Mine still isnt perfectly setup to match the actual hardware since mines set to 14 cores instead of 7 cores with 2 threads per core. I am able to compile it with my allocated 14 cores and run it via SvtHevcEncApp and ffmpeg just fine (once i figured out all the correct flags in ffmpeg durp). This is all in clearlinux which is not supported from what i can tell, what OS are you running? I did not have to modify the march in cmake for my configuration for it to work. Can you try dropping your OC back to stock, maybe it has some instability though most 1700s are able to hit that according to silicon lottery but it is hard to diagnose your issue without the logs on your failed compile and with the possibility of a none stable OC. I have also attached the output of the encoder running with the same parameters that you entered and it finishing, ignore the 2.12 fps lol i was also running another encode at the same time.

SvtHevcEncApp -i output.yuv -w 1920 -h 1080 -b out.265
-------------------------------------------
SVT-HEVC Encoder
SVT [version]:	SVT-HEVC Encoder Lib v1.3.0
SVT [build]  :	GCC 9.1.1 20190724 gcc-9-branch@273755	 64 bit
LIB Build date: Jul 27 2019 22:07:31
-------------------------------------------
Number of logical cores available: 14
Number of PPCS 107
------------------------------------------- 
SVT [config]: Main Profile	Tier (auto)	Level (auto)	
SVT [config]: EncoderMode / Tune					: 7 / 1 
SVT [config]: EncoderBitDepth / CompressedTenBitFormat / EncoderColorFormat 	: 8 / 0 / 1
SVT [config]: SourceWidth / SourceHeight					: 1920 / 1080 
SVT [config]: FrameRate / Gop Size						: 60 / 64 
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure		: 3 / 0 / 2 
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange			: CQP / 32 / 17 / 1 
SVT [config]: BitRateReduction / ImproveSharpness				: 0 / 0 
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV 	: 1 / 1 / 0 / 0
------------------------------------------- 

SVT [WARNING] Elevated privileges required to run with real-time policies! Check Linux Best Known Configuration in User Guide to run application in real-time without elevated privileges!

Encoding       480
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames		Frame Rate		Byte Count		Bitrate
         480		60.00 fps		   1282337		1282.34 kbps


Channel 1
Average Speed:		2.12 fps
Total Encoding Time:	226897 ms
Total Execution Time:	239321 ms
Average Latency:	49386 ms
Max Latency:		68302 ms
Encoder finished


luis@clearlinux~ $ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       40 bits physical, 48 bits virtual
CPU(s):              14
On-line CPU(s) list: 0-13
Thread(s) per core:  1
Core(s) per socket:  14
Socket(s):           1
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD Ryzen 7 1700 Eight-Core Processor
Stepping:            1
CPU MHz:             2994.225
BogoMIPS:            5988.45
Virtualization:      AMD-V
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-13
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good nopl cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw perfctr_core ssbd ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 virt_ssbd arat npt nrip_save

**Comment by luigi311** [comment]
@tianjunwork 
> Could you change the cmake flag “-march=native” to "–mavx" in CMakeLists.txt under root and build it again? Please pull the latest code.

 Any reason to use mavx instead of znver1 as the architecture? znver1 is the march for zen1 processors while from my understanding mavx is just a generic way to tell gcc to compile with avx support. Looks like gcc points to bdver4 by default with native for our CPUs which is back to the excavator days so i will try switching it to znver1.

**Comment by tianjunwork** [comment]
Hi @luigi311, I am not familiar with configurations on AMD so can't recommend specific settings. Please go ahead with your experiments.

**Comment by luigi311** [comment]
Didn't seem to make a difference for me performance wise or anything else that I noticed going from the default configuration to znver1. Also if he makes the change he would have to append "ON" to the option so it is selected and used since the ON flag was removed recently correct?

**Comment by tianjunwork** [comment]
Yes, -march=native is turned off recently.

**Comment by luigi311** [comment]
@mbake5 
The changes you are going to make in CMakeList.txt is 
on **line 99**
    option(NATIVE "Build for native performance (march=native)")
to 
    option(NATIVE "Build for native performance (march=znver1)" ON)
or
    option(NATIVE "Build for native performance (march=mavx)" ON)

**and on line 108**
     list(APPEND flags_to_test -march=native)
to
     list(APPEND flags_to_test -march=znver1)
or
     list(APPEND flags_to_test -march=mavx)

**Comment by 1480c1** [comment]
Alternatively, you can do `export CFLAGS="-march=native"` since cmake will use the env CFLAGS

**Comment by luigi311** [comment]
I did not even consider that. I would recommend that since it is less error prone lol.

**Comment by luigi311** [comment]
Looking through the issues in SVT-AV1 someone mentioned a socket limit of 16, setting my virtual machine to greater than 16 sockets causes the same issues he is having even pointing to the same error line that he is getting in gdb. What i am not sure of is why he is hitting that limit with 14 or 16, when i set mine to match his information of 14 sockets or 16 it works fine but when i set it to 17 or higher the error is triggered. 

Based on the information from over there and some quick testing the error is caused by this line 
https://github.com/OpenVisualCloud/SVT-HEVC/blob/cf379114cd03fd2d36c582c2b639de5df8a5e5f8/Source/Lib/Codec/EbEncHandle.c#L404-L406

due to the socket_id > 15 portion if there exists more than 16 sockets in the system it will cause it to throw an error. Is there a reason for this inclusion? Along with the MAX_PROCESSOR_GROUP setting in the same file.

**Comment by tianjunwork** [comment]
Hi @luigi311 thanks for doing all the debugging. 
A socket is the physical socket where the physical CPU capsules are placed. The reason of hard code to 16 is that the most commonly seen number of sockets is 2,4 on Xeon. 
I am not sure about the theory max socket number. And how to setup a system to test and guarantee the performance.
Could you share with me how to set the number of socket on vm and the practical usage of this configuration?

**Comment by luigi311** [comment]
@tianjunwork Yeah ive never really seen anything more than a quad socket motherboard so i never even considered it. It seems to only really occur in virtual machine environments where the end user is not allowed to modify the configuration file from the system default because otherwise they could just set it to use cores and threads instead of sockets and call it done. 
This is easy to configure in KVM by changing the xml with the following settings
`<vcpu placement='static'>64</vcpu>` 
where 64 is the number of virtual cpus in total
```
<cpu mode='host-passthrough' check='none'>
    <topology sockets='64' cores='1' threads='1'/>
</cpu>
```
 Where sockets='64' is the amount of sockets and should match up with the total virtual cpus. 

There should not be a loss in performance when switching from cores to sockets. There is a performance loss by utilizing more virtual cpus than physical cpus due to more switching occurring but it should not be massive within reason. It should also be very similar if you are using the same amount of vcpu as there are pcpu if you are only changing it to be configured in socket mode than cores/threads. Vsphere also supports this by increasing the number of virtual sockets and lowering the number of cores per socket.

**Comment by luigi311** [comment]
@tianjunwork If you get the chance can you validate my pull request #312 once you get the VM configured with sockets instead of cores.
