### ISSUE TITLE
the SSIM/PSNR quality of P422/444 do not have the same BD-rate Mx increasing curve as P420, especially for encode mode3&4 and 4K. 

### ISSUE THREAD

**Issue by wangjingz** [OpenVisualCloud/SVT-HEVC#293]
****Issue:** the quality of P422/444 do not have the same BD-rate Mx increasing curve as P420, especially for encode mode3&4 and 4k resolution.** 

4k for example: 

**4K P420**   Clip | PSNR | SSIM | PSNR + SSIM | BDRate Cost
-- | -- | -- | -- | --
svt-hevc | Y | U | V | YUV | Y | U | V | YUV | Y | YUV
HEVC_M1 vs   HEVC_M0 | 1.7% | 1.5% | 1.8% | 1.7% | 0.4% | 0.6% | 0.7% | 0.4% | 1.1% | 1.1% | 1.1%
HEVC_M2 vs   HEVC_M0 | 2.3% | 1.2% | 1.9% | 2.1% | 0.4% | 0.4% | 0.8% | 0.4% | 1.3% | 1.2% | 1.3%
HEVC_M3 vs   HEVC_M0 | 4.6% | 3.5% | 4.3% | 4.4% | 2.0% | 2.7% | 3.4% | 2.2% | 3.3% | 3.3% | 3.3%
HEVC_M4 vs   HEVC_M0 | 8.4% | 7.4% | 8.4% | 8.3% | 6.0% | 6.4% | 7.3% | 6.1% | 7.2% | 7.2% | 7.2%
HEVC_M5 vs   HEVC_M0 | 11.3% | 11.9% | 13.0% | 11.6% | 8.0% | 11.1% | 12.2% | 8.5% | 9.7% | 10.1% | 9.9%
HEVC_M6 vs   HEVC_M0 | 15.1% | 15.9% | 17.0% | 15.4% | 10.8% | 15.1% | 16.2% | 11.5% | 12.9% | 13.5% | 13.2%
HEVC_M7 vs   HEVC_M0 | 21.0% | 22.2% | 23.3% | 21.4% | 16.4% | 22.5% | 23.1% | 17.3% | 18.7% | 19.4% | 19.0%
HEVC_M8 vs   HEVC_M0 | 22.9% | 23.5% | 24.7% | 23.2% | 17.6% | 24.3% | 25.0% | 18.6% | 20.3% | 20.9% | 20.6%
HEVC_M9 vs   HEVC_M0 | 27.1% | 26.0% | 27.4% | 27.0% | 19.7% | 26.5% | 27.4% | 20.8% | 23.4% | 23.9% | 23.7%
HEVC_M10 vs   HEVC_M0 | 35.2% | 34.3% | 36.4% | 35.2% | 27.6% | 37.9% | 39.8% | 29.1% | 31.4% | 32.2% | 31.8%
HEVC_M11 vs   HEVC_M0 | 40.2% | 37.3% | 39.1% | 39.7% | 28.1% | 39.4% | 40.5% | 29.6% | 34.1% | 34.7% | 34.4%

**all P422**   clips  Only 4K | PSNR | SSIM | PSNR + SSIM | BDRate Cost
-- | -- | -- | -- | --
svt-hevc | Y | U | V | YUV | Y | U | V | YUV | Y | YUV
HEVC_M1 vs   HEVC_M0 | 0.9% | -0.8% | -0.6% | 0.2% | -0.8% | -1.8% | -1.8% | -0.9% | 0.0% | -0.4% | -0.2%
HEVC_M2 vs   HEVC_M0 | -5.9% | -11.7% | -11.7% | -8.5% | -7.9% | -13.1% | -13.1% | -8.4% | -6.9% | -8.5% | -7.7%
HEVC_M3 vs   HEVC_M0 | -29.8% | -41.6% | -42.2% | -35.2% | -31.3% | -38.9% | -41.0% | -32.1% | -30.5% | -33.7% | -32.1%
HEVC_M4 vs   HEVC_M0 | -27.8% | -39.4% | -40.0% | -33.1% | -29.2% | -36.9% | -39.0% | -30.1% | -28.5% | -31.6% | -30.0%
HEVC_M5 vs   HEVC_M0 | -16.3% | -17.0% | -17.2% | -16.7% | -16.5% | -18.2% | -20.5% | -16.8% | -16.4% | -16.7% | -16.6%
HEVC_M6 vs   HEVC_M0 | -18.2% | -20.4% | -20.8% | -19.3% | -18.6% | -20.3% | -23.1% | -18.9% | -18.4% | -19.1% | -18.8%
HEVC_M7 vs   HEVC_M0 | -23.0% | -30.3% | -31.5% | -26.6% | -23.1% | -24.3% | -27.3% | -23.4% | -23.1% | -25.0% | -24.0%
HEVC_M8 vs   HEVC_M0 | -20.0% | -26.9% | -28.5% | -23.6% | -19.6% | -19.4% | -22.3% | -19.7% | -19.8% | -21.6% | -20.7%
HEVC_M9 vs   HEVC_M0 | -19.1% | -26.1% | -27.9% | -22.7% | -18.7% | -18.3% | -21.4% | -18.8% | -18.9% | -20.8% | -19.8%
HEVC_M10 vs   HEVC_M0 | -11.5% | -18.6% | -20.8% | -15.2% | -9.1% | 0.4% | -0.3% | -8.2% | -10.3% | -11.7% | -11.0%
HEVC_M11 vs   HEVC_M0 | -17.2% | -19.8% | -20.9% | -18.6% | -16.3% | -1.0% | -1.3% | -14.7% | -16.8% | -16.7% | -16.7%

**Encode command Line such as:** 
./SvtHevcEncApp -encMode 0  -w 3840  -h 2160  -i yuvs/stream_P444.yuv  -q 22  -fps 60  -b bitstreams/4k_60Hz_P444_Q22.bin   -n 300  -intra-period 55  -bit-depth 10 -color-format 3
 **use ffmpeg to caculate psnr/ssim:** 
./ffmpeg -r 25  -i bitstreams/4k_60Hz_P444_Q22.bin -s:w 3840x2160 -pix_fmt yuv444p10le -f rawvideo -i yuvs/stream_P444.yuv -lavfi ssim="stats_file=3840x2160_10bit_60Hz_P444.SSIM;[0:v][1:v]psnr=stats_file=3840x2160_10bit_60Hz_P444.PSNR" -f null - 2> ./log/3840x2160_10bit_60Hz_P444.PSNR_SSIM
.

**Comment by kelvinhu325** [comment]
In P422 test, M0 shows bigger bitstream size and higher Luma PSNR than M3, while shows worse Chroma PSNR than M3, once I enable inter search only luma instead of luma + chroma for M0~6, then M0 gets best Luma/Chroma PSNR and smallest bitstream size.
Supposed full(luma + chroma) search should get better prediction than best(only luma) search, but it does not for M0~6, in current implementation, P422 chroma search is still based on 420 data, probable there are somethings wrong on chroma search reference data preparing for P422.

**Comment by kelvinhu325** [comment]
In P422 test, M0 shows bigger bitstream size and higher Luma PSNR than M3, while shows worse Chroma PSNR than M3, once I enable inter search only luma instead of luma + chroma, then M0 gets best Luma/Chroma PSNR and smallest bitstream size. supposed full(luma + chroma) search should get better prediction than best(only luma) search, but it does not, in current implementation, P422 chroma search is still based on 420 data, probable there are somethings wrong on chroma search reference data preparing for P422.

**Comment by tianjunwork** [comment]
closed by #294
