### ISSUE TITLE
[macOS]Fail early in CMake

### ISSUE THREAD

**Issue by yurikoles** [OpenVisualCloud/SVT-HEVC#390]
Why fail at 70% of build process but not in CMake step?
```
Source/Lib/Codec/EbThreads.c:30:2: error: OS/Platform not supported.
#error OS/Platform not supported.
```

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-HEVC/issues/38
https://github.com/OpenVisualCloud/SVT-HEVC/pull/135

Currently macOS support is considered low priority

**Comment by tianjunwork** [comment]
Hi @yurikoles you mean exiting once CMake detect unsupported OS?
MacOS is not supported yet and being worked on with very low priority.

**Comment by yurikoles** [comment]
Yes, since it doesn't work either way now, why fail at 70% and not on the configure step.

**Comment by tianjunwork** [comment]
There are some compilation errors on macOS as known issue. We yet claim the support of macOS officially.
Since supporting macOS is being worked on still(with low priority though), it didn't exit during configure step.
Does it bother you so much in your environment? Could you help submitting a PR shutting down the configure process on macOS? We can have it until the support is ready on macOS. Thank you.

**Comment by 1480c1** [comment]
Technically speaking, #135 does allow for compilation on macOS, however, due to https://github.com/OpenVisualCloud/SVT-HEVC/issues/274, there is a runtime error when running on macOS without AVX2 support

**Comment by 1480c1** [comment]
This can be closed
