### ISSUE TITLE
An error(Error encoding at channel 1! Check error log file for more details ...Segmentation fault) occurred in running the following command line.

### ISSUE THREAD

**Issue by GuCaixuan** [OpenVisualCloud/SVT-HEVC#64]
Hi,
An error (Error encoding at channel 1! Check error log file for more details ...Segmentation fault) occurred in running the following command line.

SvtHevcEncApp -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv  -b width_height_test_M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q16_TUNE1_4060_1984.265  -errlog width_height_test_M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q16_TUNE1_4060_1984.errlog  -w 4060  -h 1984  -bit-depth 10  -fps 60  -intra-period 55  -n 100  -compressed-ten-bit-format 0  -q 16  -encMode 9  -rc 0  -tune 1

The SVT version we used is v1.3.0 from master.

Thanks!

**Comment by hassount** [comment]
@GuCaixuan 
Thank you for your feedback. 

From the command line there seems to be a mismatch between the input height of the original yuv input and the height inputted to the encoder. Is that intended ?

**Comment by GuCaixuan** [comment]
**@hassount** 
Yes, it is.

Thanks!

**Comment by hassount** [comment]
@GuCaixuan 
are you expecting the encoder to resize the input on its own ? or are you testing that it will be able to encode garbage video ?

**Comment by GuCaixuan** [comment]
@hassount 
With the following command line, the encode is executed correctly, and the bitstream obtained is resized successfully.
The only difference between the failed command line and the following is that the value of "-h" is 1104 .

SvtHevcEncApp -i Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv  -b width_height_test_M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q16_TUNE1_4060_1104.265  -errlog width_height_test_M9_Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420_Q16_TUNE1_4060_1104.errlog  -w 4060  **-h 1104**  -bit-depth 10  -fps 60  -intra-period 55  -n 100  -compressed-ten-bit-format 0  -q 16  -encMode 9  -rc 0  -tune 1

**Comment by hassount** [comment]
@GuCaixuan 
Thank you for the additional information. 
the library will not be able to know the original size of the video from a yuv file and it will depend on the input width and height passed in by the user. That said, if the output of the encode with -h 1104 looks good, it means that most likely the actual height of the input file "Netflix_FoodMarket2_4096x2160_10bit_60Hz_P420.yuv" is 4096x1104. 

Bottom line what you see above is an expected behavior: 

If the encoder gets a width and height that are mismatching with the original dimensions of the input video then it will start encoding garbage video (it will be all green likely). In which case, the prediction will be too bad and the encoder needs to output too many bits to compensate for the bad prediction. @ qp 16, the residual is barely quantized and the output bitrate will probably be in the few hundred Mbps range. in which case the encoder would usually throw an error: 
"Error: CopyRbspBitstreamToPayload: output buffer too small"
That is because the output buffers are too small to handle this kind of output. The encoder is usually designed to operate in bitrate ranges that are <100Mbps.

**Comment by tianjunwork** [comment]
@GuCaixuan 
Please note, encoder doesn't resize the video, -w and -h is the size of the input video, not output.
Could you figure out the real size of the input video and set them to the encoder? If you still see the error, let us know. Thank you.
